### ISSUE TITLE
Убрать использование конструкций try/catch из классов команд.

### ISSUE THREAD

**Issue by Knebergish** [NetCrackerO2/ScheduleProject#34]
Отлов исключений и вывод их сообщения происходит в методе start() класса Controller. Дополнительное использование этих конструкций внутри классов команд уменьшает производительность программы и загрязняет код.

**Comment by AsGreyWolf** [comment]
Проверки в командах все равно нужны

**Comment by Knebergish** [comment]
Большинство комманд мне удалось избавить от этих конструкций, не изменяя их функционала. Остались только команды редактирования. Там чёт страшно, я не полез.
